plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.loaraid'
version = '0.0.1-SNAPSHOT'
description = 'loaraid'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	//env
	implementation 'io.github.cdimascio:dotenv-java:3.0.0'

	//api 처리 webflex/json 파싱
	implementation 'org.springframework.boot:spring-boot-starter-webflux' // WebClient
	implementation 'com.fasterxml.jackson.core:jackson-databind'        // JSON 파싱

	//flyway
	implementation 'org.flywaydb:flyway-mysql'
	implementation 'org.flywaydb:flyway-core:11.13.2'

	implementation 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
